### ISSUE TITLE
Convert action to use docker

### ISSUE THREAD

**Issue by mithro** [mithro/actions-includes#1]
The tool needs;
 - Latest Python version to get order preserving dicts.
 - python3-yaml installed.
 
These dependencies mean it would work well as a docker action.

**Comment by mithro** [comment]
This is now done I think;
 - https://github.com/mithro/actions-includes/blob/main/docker/Dockerfile
 - https://github.com/mithro/actions-includes/blob/main/action.yml

**Comment by mithro** [comment]
There could still be some optimization I think?

**Comment by laughedelic** [comment]
Is there a way to have those deps, but avoid using Docker? I think latest Python is pre-installed in the runner, maybe installing the other dependency in place will do? 

The problem with docker-based actions is that they add an image preparation (pull?) step to the job an sometimes it's slower than just installing what you need as the part of the action.

**Comment by umarcor** [comment]
@laughedelic although image preparation might be slow if done naively, we put effort in reducing it to the minimum. As seen in https://github.com/mithro/actions-includes/blob/main/action.yml#L25 the image is pre-generated and available in GitHub's own registry. Therefore, it is very arguable whether pulling that image only (which should be implicitly cached/proxied close to the runners) is slower than installating Python dependencies from external locations (and building the dependencies if necessary). That might be true in some cases but it's not a rule of thumb. Moreover, #9 is work in progress to further reduce the size of the image by using Alpine instead of Debian. Did you actually find performance issues?
